// Auto-writes lib/build-version.ts from the current git commit before every
// build/dev. The short SHA + commit count change on every commit, so the app
// always shows which commit it was built from. Safe when git is unavailable
// (some sandboxed CI) — falls back to 'dev'. This file is gitignored on
// purpose so it never creates commit churn; it's regenerated each build.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outPath = join(here, '..', 'lib', 'build-version.ts');

function git(cmd) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
  } catch {
    return '';
  }
}

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version || '0.0.0';
const commit = git('git rev-parse --short HEAD') || 'dev';
const count = (() => {
  const c = git('git rev-list --count HEAD');
  return c && /^\d+$/.test(c) ? Number(c) : 0;
})();
const date = git('git show -s --format=%cI HEAD') || '';

const content = `// AUTO-GENERATED by scripts/write-version.mjs — do not edit by hand.
// Regenerated before every build/dev to reflect the current git commit.
export const BUILD_VERSION = ${JSON.stringify(version)};
export const BUILD_COMMIT = ${JSON.stringify(commit)};
export const BUILD_COMMIT_COUNT = ${count};
export const BUILD_DATE = ${JSON.stringify(date)};
`;

writeFileSync(outPath, content, 'utf8');
console.log(`[write-version] ${version} · ${commit} (${count} commits)${date ? ` · ${date.slice(0, 10)}` : ''}`);
