import { AgentTiming } from './types';
import { generateId } from './id';

/**
 * Per-execution timing helpers. Timestamps are application-authoritative
 * (captured at the fetch boundary) — NOT text generated by the model. This app
 * has no streaming, so firstTokenAt is set to completedAt on completion (the
 * spec explicitly permits this for non-streaming providers).
 */

export function startAgentTiming(): AgentTiming {
  const startedAt = new Date().toISOString();
  return { executionId: generateId(), startedAt };
}

function msBetween(aIso: string, bIso: string): number {
  const a = Date.parse(aIso);
  const b = Date.parse(bIso);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return 0;
  return Math.max(0, b - a);
}

/** Complete a timing object: sets completedAt, firstTokenAt (= completedAt for
 * non-streaming), and all derived durations. Returns a NEW object. */
export function completeAgentTiming(t: AgentTiming): AgentTiming {
  const completedAt = new Date().toISOString();
  const totalDurationMs = msBetween(t.startedAt, completedAt);
  return {
    ...t,
    firstTokenAt: t.firstTokenAt ?? completedAt,
    completedAt,
    timeToFirstTokenMs: t.firstTokenAt ? msBetween(t.startedAt, t.firstTokenAt) : totalDurationMs,
    generationDurationMs: totalDurationMs,
    totalDurationMs,
  };
}

/** Stop the timer on failure: sets failedAt + totalDurationMs (no completion). */
export function failAgentTiming(t: AgentTiming): AgentTiming {
  const failedAt = new Date().toISOString();
  return { ...t, failedAt, totalDurationMs: msBetween(t.startedAt, failedAt) };
}

/** Format ms as a short human label: "8.4s", "412ms". */
export function formatDuration(ms: number | undefined): string {
  if (ms == null || !Number.isFinite(ms)) return '';
  if (ms < 1000) return `${Math.round(ms)}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}
